### PR TITLE
Fix: Added missing fulfilledFragments to generated initializers

### LINKED ISSUE #2989: Broken codegen for nested fragments with enum
### Summary

When nesting fragments and enums, the `"__fulfilled"` set is missing some cases and `.asSomething()` operators fail.

### Version

1.1.3

### Steps to reproduce the behavior

Here is a simplified schema needed to reproduce:

```gql
fragment ConversationItemFragment on ConversationItem {
    ... on Message {
        ...MessageFragment
    }
    ... on ConversationActivity {
        ...ConversationActivityFragment
    }
}

fragment MessageFragment on Message {
    id
    content {
        ...MessageContentFragment
    }
}

fragment MessageContentFragment on MessageContent {
    ... on TextMessageContent {
        ...TextMessageContentFragment
    }
    ... on ImageMessageContent {
        ...ImageMessageContentFragment
    }
}

fragment TextMessageContentFragment on TextMessageContent {
    text
}

fragment ImageMessageContentFragment on ImageMessageContent {
    url
}
```

Here is the output of the codegen with:

```swift
                        schemaNamespace: "GQL",
                        options: .init(
                            selectionSetInitializers: [
                                .fragment(named: "ConversationItemFragment"),
                                .fragment(named: "MessageFragment"),
                            ],
```

```swift

extension GQL {
  struct ConversationItemFragment: GQL.SelectionSet, Fragment {
    struct AsMessage: GQL.InlineFragment {
      init(
        id: GQL.UUID,
        content: MessageFragment.Content,
      ) {
        self.init(_dataDict: DataDict(data: [
          "__typename": GQL.Objects.Message.typename,
          "id": id,
          "content": content._fieldData,
          "__fulfilled": Set([
            ObjectIdentifier(Self.self),
            ObjectIdentifier(ConversationItemFragment.self),
            ObjectIdentifier(MessageFragment.self)
          ])
        ]))
      }
    }
  }
}


extension GQL {
  struct MessageFragment: GQL.SelectionSet, Fragment {
    struct Content: GQL.SelectionSet {
      struct AsTextMessageContent: GQL.InlineFragment, ApolloAPI.CompositeInlineFragment {
        init(
          text: String
        ) {
          self.init(_dataDict: DataDict(data: [
            "__typename": GQL.Objects.TextMessageContent.typename,
            "text": text,
            "__fulfilled": Set([
              ObjectIdentifier(Self.self),
              ObjectIdentifier(MessageFragment.Content.self),
              ObjectIdentifier(MessageContentFragment.self),
              ObjectIdentifier(TextMessageContentFragment.self)
            ])
          ]))
        }
      }
    }
  }
}
```
Then when I try to use the generated initializer:

```swift
let item = GQL.ConversationItemFragment.AsMessage(
  id: GQL.UUID(),
  content: .AsTextMessageContent(text: "Hello world!").asRootEntityType
)

func foo(_ item: GQL.ConversationItemFragment) {
  guard let message = item.asMessage?.fragments.messageFragment else {
    print("asMessage is broken")
  }
  guard let textContent = message.content.fragments.messageContentFragment.asTextMessageContent else {
    print("asTextMessageContent is broken")
  }
  print("Success \(textContent)")
}

foo(item.asRootEntityType)
```
It prints `asTextMessageContent is broken`.

This is because the definition of `asTextMessageContent` expects some `MessageContentFragment.AsTextMessageContent` type. But such type is not listed in the `__fulfilled` set. 

```swift
  struct MessageContentFragment: GQL.SelectionSet, Fragment {
    var asTextMessageContent: AsTextMessageContent? { _asInlineFragment() }
  }
```

```
(lldb) po ObjectIdentifier(GQL.MessageContentFragment.AsTextMessageContent) == ObjectIdentifier(GQL.TextMessageContentFragment)
false

(lldb) po ObjectIdentifier(GQL.MessageContentFragment.AsTextMessageContent) == ObjectIdentifier(GQL.MessageContentFragment)
false

(lldb) po ObjectIdentifier(GQL.MessageContentFragment.AsTextMessageContent) == ObjectIdentifier(GQL.MessageFragment.Content)
false
```

### Logs

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by AnthonyMDev**
Fixes #2989 

The generated initializers were missing the fulfilled fragments in certain cases. When you were merging in selection sets from a named fragment, we only were including the root of that fragment. This was missing the nested type cases of that fragment, and was just completely wrong if you were actually merging from a nested entity field on that named fragment.

This now uses the merged sources to calculate all of the selection sets that would be fulfilled from the fragment root to the merged source.

### CODE REVIEW

File: Sources/ApolloCodegenLib/Templates/SelectionSetTemplate.swift [hunk 1]
```diff
@@ -483,29 +483,27 @@ struct SelectionSetTemplate {
   private func InitializerFulfilledFragments(
     _ selectionSet: IR.SelectionSet
   ) -> TemplateString {
-    var fulfilledFragments: [String] = ["Self"]
+    var fulfilledFragments: OrderedSet<String> = []
 
-    var next = selectionSet.scopePath.last.value.scopePath.head
-    while next.next != nil {
-      defer { next = next.next.unsafelyUnwrapped }
+    var currentNode = Optional(selectionSet.scopePath.last.value.scopePath.head)
```
Comment (BobaFetters) [inline Sources/ApolloCodegenLib/Templates/SelectionSetTemplate.swift:488]: Like the renaming here from just using `next`

**Review by BobaFetters — APPROVED** [review]
This looks good to me, nice work!
