### PR TITLE
fix: Xcode integration for Swift Package Plugins

### LINKED ISSUE #2543: Unable to run code generation
## Bug report

Installing Apollo 1.0.0 via Cocoapods results in code generation error.

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 1.0.0
- Xcode version: 14.0.1
- Swift version: 5.7
- Package manager: N/A
- Cocoapods version: 1.11.3

## Steps to reproduce

`pod init`

Add `pod 'Apollo'`

`pod install`

`./Pods/Apollo/apollo-ios-cli init --schema-name MySchema`
`./Pods/Apollo/apollo-ios-cli generate` 

```
ApolloCodegenLib/resource_bundle_accessor.swift:11: Fatal error: could not load resource bundle: from /Users/xxx/ProjectName/Pods/Apollo/Apollo_ApolloCodegenLib.bundle or /Users/xxx/Library/Caches/CocoaPods/Pods/Release/Apollo/1.0.0-95555/.build/arm64-apple-macosx/release/Apollo_ApolloCodegenLib.bundle
zsh: trace trap  ./Pods/Apollo/apollo-ios-cli generate
```

## Further details

Note that cocoapods is installed using Hombrew.

### PR DESCRIPTION
**Pull request by calvincestari**
Fixes #2543

The Xcode integration for SwiftPM plugins was not working correctly.

This PR fixes than through the following:
* We had to add support for `XcodePluginContext` to correctly route the command
* Accept the `--target` command line option which was being sent by Xcode

### CODE REVIEW

File: Package.swift [hunk 1]
```diff
@@ -62,9 +62,6 @@ let package = Package(
       exclude: [
         "Info.plist",
         "Frontend/JavaScript",
-      ],
```
Comment (calvincestari) [inline Package.swift:65]: This was forgotten about in #2548 resulting in a warning in Xcode.

File: .circleci/config.yml [hunk 2]
```diff
@@ -95,15 +95,25 @@ commands:
...
+          name: CocoaPods - CLI Test (generate)
+  swiftpm_plugin_test:
+    steps:
+      - run:
+          working_directory: Tests/CodegenCLITests/swiftpm-test/
+          command: swift build
+          name: SwiftPM - Build package
+      - run:
+          working_directory: Tests/CodegenCLITests/swiftpm-test/
+          command: swift package plugin --allow-writing-to-package-directory apollo-generate --verbose
```
Comment (calvincestari) [inline .circleci/config.yml:115]: We only test the `generate` command here because we needed have an existing JSON config file to prevent codegen finding all the test graphQL definition files in the `.build` folder. We're going to fix that behaviour in #2552.

**Review by AnthonyMDev — APPROVED** [review]
Thanks for this!
