### PR TITLE
Fix: Pruning generated files for relative operations

### LINKED ISSUE #2969: Pruning generated files for .relative(subpath:) operations deletes only
### Summary

When generating code with `operations: .relative(subpath: "somepath")`, and with `pruneGeneratedFiles` not set (assuming defaulting to true), the after 1 generate run it only deletes the operations. Then after a second run it regenerates them.

If you repeat this process it should repeat the pattern, i.e. delete only -> regenerate -> delete only -> regenerate -> etc.

### Version

1.0.7

### Steps to reproduce the behavior

Create a codegen project with `operations: .relative(subpath: "somepath")`, and with `pruneGeneratedFiles` not set, then repeatedly execute codegen. You should see the operations be deleted and regenerated on each subsequent execution.

### Logs

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by BobaFetters**
Updating code generation to always use resolved file paths when writing files, and getting lists of generated files to account for errors with files being deleted by mistake when symlink directories are used.

closes #2969

### CODE REVIEW

File: Sources/ApolloCodegenLib/Glob.swift [hunk 1]
```diff
@@ -177,7 +177,7 @@ public struct Glob {
           excludedSet.intersection(url.pathComponents).isEmpty
         else { continue }
 
-        directories.append(url)
+        directories.append(url.resolvingSymlinksInPath())
```
Comment (BobaFetters) [inline Sources/ApolloCodegenLib/Glob.swift:180]: The code change in `ApolloCodegen` to resolve symlinks does not actually solve the issue of `/private/var` vs `/var` paths in test because neither is marked as a symlink. However, running `.resolvingSymlinksInPath()` does remove `/private` from paths when it exists, so to be able to run tests for this issue I also had to change this line.

Thoughts on this? Or other suggestions of maybe handling this?

File: Sources/ApolloCodegenLib/ApolloCodegen.swift [hunk 2]
```diff
@@ -462,9 +462,24 @@ public class ApolloCodegen {
...
+    var existingPaths: Set<String> = try globs.reduce(into: []) { partialResult, glob in
       partialResult.formUnion(try glob.match())
     }
+    
+    try resolveSymlinksInPaths(&existingPaths)
+    
+    return existingPaths
+  }
+  
+  private static func resolveSymlinksInPaths(_ paths: inout Set<String>) throws {
```
Comment (AnthonyMDev) [inline Sources/ApolloCodegenLib/ApolloCodegen.swift:474]: This function looks like it's just removing symlink paths, not actually resolving the symlinks. Is that correct?

If so, we should probably change the name of the function. But there is also something awkward about this, because there is implicit knowledge that the paths returned from the glob have _both_ the path with and without the symlink in the `Set`. Is that correct?

I'm feeling like we should be expressing this better and removing the need for implicit knowledge here. Especially since you are now calling `resolvingSymlinksInPath()` inside of the `Glob` code.

If we are going to resolve the symlinks in the Glob, I'm not even clear why we also need this here? I know we had talked about this being the responsibility of the Codegen, not the `Glob` implementation, but it feels like we are violating that anyways now.

File: Tests/ApolloCodegenTests/ApolloCodegenTests.swift [hunk 3]
```diff
@@ -1446,6 +1446,60 @@ class ApolloCodegenTests: XCTestCase {
...
+    )
+
+    // then
+    
+    // running codegen multiple times to validate symlink related file creation/deletion bug
+    try ApolloCodegen.build(with: config, rootURL: directoryURL)
+    expect(ApolloFileManager.default.doesFileExist(atPath: fileValidationPath)).to(beTrue())
+    
+    try ApolloCodegen.build(with: config, rootURL: directoryURL)
+    expect(ApolloFileManager.default.doesFileExist(atPath: fileValidationPath)).to(beTrue())
```
Comment (AnthonyMDev) [inline Tests/ApolloCodegenTests/ApolloCodegenTests.swift:1497]: Just confirming here, without the code added in this PR, this test passes on the first expectation, fails the second, and passes the third, right?

Comment (BobaFetters) [reply Tests/ApolloCodegenTests/ApolloCodegenTests.swift:1497]: Correct

File: Sources/ApolloCodegenLib/ApolloCodegen.swift (hunk 2 above)
Comment (BobaFetters) [reply Sources/ApolloCodegenLib/ApolloCodegen.swift:474]: Good point renaming the function would make since. And yes, the issue currently is that both a real path and symlink path to a file exist in the Set which causes the deletion.

Also the reason `resolvingSymlinksInPath()` is called in `Glob` is specifically due to needing to make sure paths in tests are resolved from `/private/var/....` to just `/var/....`, however that change would not actually fix the non-test issue because the `directoryURL` used at that point in the code would not actually be the symlinked path. The code I showed you earlier where we could do the symlink resolution in `Glob.expand` by building out the paths before adding them to the Set in the return could potentially solve for both the test and non-test issue, will have to check to verify, and if so we may just need to do that since it appears we will need some change inside of `Glob` anyways which is what we were trying to avoid.

Comment (AnthonyMDev) [reply Sources/ApolloCodegenLib/ApolloCodegen.swift:474]: I don't mind if we do this in the `Glob`, but I feel like we need a clear definition of what we are actually doing.

The real issue here is one of separation of responsibilities.  It's a current behavior that the output of the `Glob` has duplicated paths. That is – two paths that actually point to the same place because of symlinks. If we decide that is an acceptable behavior of `Glob`, because it is just used to pattern match the paths, and there _are_ two paths there technically, then that's okay. Let's document that behavior and then deduplicate the paths in `ApolloCodegen`, as we are doing. In which case the fix for the unit tests `/private/var` needs a different fix probably.

I think it's also reasonable to say that the behavior of the `Glob` struct should do the resolving of symlinks and deduplication of paths, ensuring that its output only points to a single file one time, regardless of how many different paths are symlinked to the file's _actual_ path. If we do that, we can fix the problem in one place, and we should be documenting (and probably testing) that as an intended and defined behavior of our `Glob` matching object.

I don't have a strong opinion on where we do this, only that we do it in a way that defines a responsibility of a single object that is sensible; is documented; is tested; and works in consistently in every case (of course bugs are bugs, so "every case" means "every known case"). 

I think I might be misunderstanding or missing some information here, but having the symlink deduplication in the codegen but also resolving symlinks in the Glob seems to be muddying the single responsibility principle here.

If there is a specific odd edge case where `/private/var` isn't being picked up as a symlink properly we can hard code in a fix for the edge case. But if we are going to resolve all symlinks lets have a clear definition of what that means, where it's happening, and why.

File: Sources/ApolloCodegenLib/Glob.swift [hunk 4]
```diff
@@ -185,7 +186,15 @@ public struct Glob {
     }
 
     return OrderedSet<String>(directories.compactMap({ directory in
-      var path = directory.appendingPathComponent(lastPart).standardizedFileURL.path
+      // build directory URL up the the '*' in the pattern, and check if it is a symlink, if so skip it
+      let symCheckURL = directory.appendingPathComponent(lastDirComponent).standardizedFileURL
```
Comment (BobaFetters) [inline Sources/ApolloCodegenLib/Glob.swift:190]: @AnthonyMDev this block can run the same symlink check for production use cases we previously had in the `ApolloCodegen` class. But keeps all symlink related checks contained within this `compactMap` call

File: Sources/ApolloCodegenLib/ApolloCodegen.swift (hunk 2 above)
Comment (calvincestari) [reply Sources/ApolloCodegenLib/ApolloCodegen.swift]: I built `Glob` to be a pattern matching engine; it expands given wildcards and outputs matching paths. IMO those should be resolved symlinks and there should _not_ be any duplicates. `Glob` is at the crux of path discovery here and it feels that should be doing the work. I don't think there is ever a need for us to know both the symlink and actual path?

File: Sources/ApolloCodegenLib/Glob.swift [hunk 5]
```diff
@@ -185,7 +186,15 @@ public struct Glob {
...
+      if let resourceValues = try? symCheckURL.resourceValues(forKeys: [.isSymbolicLinkKey]),
+         let isSymLink = resourceValues.isSymbolicLink,
+         isSymLink {
+        return nil
+      }
+      
+      var path = directory.resolvingSymlinksInPath().appendingPathComponent(lastPart).standardizedFileURL.path
```
Comment (BobaFetters) [inline Sources/ApolloCodegenLib/Glob.swift:197]: @AnthonyMDev Adding `.resolvingSymlinksInPath()` here is still necessary to resolve test use cases since the above code will never show the `/private/var/....` path as a symlink, but this call still removes the `/private` part of the path based on the [documentation](https://developer.apple.com/documentation/foundation/nsurl/1415965-resolvingsymlinksinpath) for the function call

File: Sources/ApolloCodegenLib/Glob.swift (hunk 4 above)
Comment (BobaFetters) [reply Sources/ApolloCodegenLib/Glob.swift:190]: Alternatively, I may be able to build the url up to the `*` in the pattern like we are doing here, and then run the `.resolvingSymlinksInPath` on that URL, and then appending the final path component which could cover both production and test use cases without needing to access resource keys and result in less code. Going to look into that now.

Comment (BobaFetters) [reply Sources/ApolloCodegenLib/Glob.swift:190]: Would look something like this although maybe cleaned up a little:
```
let last = parts.joined(separator: String.Globstar)
let lastParts = last.components(separatedBy: "*")
let lastDirComponent = lastParts.first ?? ""
let lastPart = lastParts.last ?? ""
....
....
....
let url = directory.appendingPathComponent(lastDirComponent).standardizedFileURL.resolvingSymlinksInPath()
var path = url.appendingPathComponent("*\(lastPart)").standardizedFileURL.path
```

**Review by calvincestari — APPROVED** [review]
This looks good Zach - thanks! Are you still iterating on the `Glob` code to simplify it?

File: Sources/ApolloCodegenLib/Glob.swift
Comment (BobaFetters) [inline Sources/ApolloCodegenLib/Glob.swift:1]: @calvincestari I ended up refactoring the `Glob` code to this so that the same code in the `compactMap` can handle both production and test use cases instead of checking resource keys for production and then always still resolving symlinks. So just tweaking how the path is built allows for just resolving symlinks for every path that comes through.

**Comment by BobaFetters** [comment]
Ok after re-reading the documentation for `.resolvingSymlinksInPaths()` I realized it only works only `file:` path schemes, so was able to move this check to filter the `includedPaths` list before returning it from the `match` function which ends up with a clean solution to this.

**Review by AnthonyMDev — APPROVED** [review]
