### PR TITLE
Fix test mock custom scalar and double nested array execution

### LINKED ISSUE #2809: Crash when using mocks for Double Nested Arrays
### Summary

I have a schema that looks something like this: 

```
type InnerObject { 
    propertyOne: Int!
    propertyTwo: Int!
}

type OuterObject { 
    propertyOne: Int!
    propertyTwo: [[InnerObject!]!]!
}
```

And I have ran codegen for this and created the mocks. When using the mocks in tests, everything compiles fine. However when i set the value of "propertyTwo" two in mocks, and then convert it to a (non-mock) graphQL object using .from(Mock<OuterObject>)  and then try to access "propertyTwo" in code, it crashes with the error
`fatalError("\(Self.self) expected data for entity.")`

### Version

1.0.5

### Steps to reproduce the behavior

- Use a schema with a property of type:
```
[[SomeObject!]!]!
```
- Generate mocks / code from it. 
- Initialize an object for the containing type use `.from(Mock<>)`
- try to access the property of double nested array type.
- Notices the crash

### Logs

_No response_

### Anything else?

Screenshot 2023-02-03 at 8 35 41 PM

Here's what the call stack looks like.

### PR DESCRIPTION
**Pull request by AnthonyMDev**
Fixes #2809 and #2928

### CODE REVIEW

File: Sources/ApolloTestSupport/TestMockSelectionSetMapper.swift [hunk 1]
```diff
@@ -0,0 +1,50 @@
+#if !COCOAPODS
+@testable import ApolloAPI
+#endif
+@testable import Apollo
```
Comment (calvincestari) [inline Sources/ApolloTestSupport/TestMockSelectionSetMapper.swift:4]: This needs to be moved up into the `#if !COCOAPODS` directive otherwise the cocoapods spec linting will fail with a warning that the file is already part of the `Apollo` module. [Part of what was fixed](https://github.com/apollographql/apollo-ios/pull/2937/files#diff-b3d3d639f815a2b3dcee78379825c377b4036869559a53c6eeb302aa1587fccfL3) for #2937.

**Review by calvincestari — CHANGES_REQUESTED** [review]
