### PR TITLE
Fix referenced input types for JSON introspection

### LINKED ISSUE #2550: Not generating code for subtypes only used as input to mutations?
## Bug report

We have been attempting to move from apollo-ios 0.53.0 to 1.0.0 and have encountered a problem where code generation doesn't seem to generate code for subtypes that are only used as input. This worked for us using version 0.53.0.

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: 1.0.0
- Xcode version: 14.0.1
- Swift version: 5.7
- Package manager: 5.7.0

## Further details

Basically we have a mutation accepting a custom type as input. The type roughly looks like this:

```graphql
enum CarProblem {
  NO_FUEL
}

input ReportCarProblemInput {
  carId: UUID!
  problem: CarProblem!
}
```

This is then used in a mutation:

```graphql
mutation ReportCarProblem($input: ReportCarProblemInput!) {
  reportCarProblem(input: $input) {
    accepted
  }
}
```

When this code is generated, there's a compiler error where the generated code for `ReportCarProblemInput` references the `CarProblem` enum, because the code for it hasn't been generated.

If I manually add a queryable field of the `CarProblem` type, and a query for it, and _then_ generate code, the generated code for `ReportCarProblemInput` works as expected.

### PR DESCRIPTION
**Pull request by AnthonyMDev**
Resolves #2550

### CODE REVIEW

File: Sources/ApolloCodegenLib/Frontend/JavaScript/src/compiler/index.ts [hunk 1]
```diff
@@ -119,12 +119,10 @@ export function compileToIR(
   function addReferencedTypesFromInputObject(
     inputObject: GraphQLInputObjectType
   ) {
-    const fields = inputObject.astNode?.fields
-    if (fields) {
-      for (const field of fields) {
-        const type = typeFromAST(schema, field.type) as GraphQLType
-        addReferencedType(getNamedType(type))
-      }    
+    const fieldMap = inputObject.getFields()
```
Comment (AnthonyMDev) [inline Sources/ApolloCodegenLib/Frontend/JavaScript/src/compiler/index.ts:122]: This is the fix. The rest is just VSCode removing white space

**Review by calvincestari — APPROVED** [review]
Minor correction of test name otherwise LGTM!

**Comment by cheif** [comment]
👏 Much appreciated! 😄
