### PR TITLE
fix: Correctly namespace schema types in operation files when a `.relative` or `.absolute` location is used

### LINKED ISSUE #2301: [Swift Codegen] Enum is missing namespace
## Bug report

Generated enum

```swift
public extension CustomerGraphQL {
  public enum ConsentType: String, EnumType {
    case GENERAL
// More cases
  }
}
```

Generated query code:

``` swift 
public class ConsentQuery: GraphQLQuery {
  public var consentType: GraphQLEnum<ConsentType>

  public init(consentType: GraphQLEnum<ConsentType>) {
    self.consentType = consentType
  }
// More code
}
```

expected code

``` swift 
public class ConsentQuery: GraphQLQuery {
  public var consentType: GraphQLEnum<CustomerGraphQL.ConsentType>

  public init(consentType: GraphQLEnum<CustomerGraphQL.ConsentType>) {
    self.consentType = consentType
  }
// More code
}
```

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: [1.0.0 Alpha 6](https://github.com/apollographql/apollo-ios/releases/tag/1.0.0-alpha.6)
- Xcode version: 13.4.1
- Swift version: 5.6.1
- Package manager: 5.6.1

## Steps to reproduce

Our generation command

```swift
  struct GenerateCode: ParsableCommand {
    static var configuration = CommandConfiguration(
      commandName: "generate",
      abstract: "Generates swift code from your schema + your operations based on information set up in the `GenerateCode` command.")

    func run() throws {
      /// The root of the target for which you want to generate code.
      let targetRootURL = SourceRootURL
        .apollo.childFolderURL(folderName: "customer-ios/graphql")

      /// The URL where the generated schema files will be written to.
      let schemaModuleURL = SourceRootURL
        .apollo.childFolderURL(folderName: "customer-ios/graphql")

      // Make sure the folders exists before trying to generate code.
      try FileManager.default.apollo.createDirectoryIfNeeded(atPath: targetRootURL.path)
      try FileManager.default.apollo.createDirectoryIfNeeded(atPath: schemaModuleURL.path)

      // Create the Codegen configuration object. For all configuration parameters see: https://www.apollographql.com/docs/ios/api/ApolloCodegenLib/structs/ApolloCodegenConfiguration/
      let codegenConfiguration = ApolloCodegenConfiguration(
        schemaName: "GraphQLApi", input: ApolloCodegenConfiguration.FileInput(schemaPath: SchemaOutputURL.path, searchPaths: ["\(targetRootURL.path)/**/*.graphql"]),
        output: ApolloCodegenConfiguration.FileOutput(
          schemaTypes: ApolloCodegenConfiguration.SchemaTypesFileOutput(
            path: schemaModuleURL.path,
            moduleType: .embeddedInTarget(name: "customer-ios"))
        )
      )

      // Actually attempt to generate code.
      try ApolloCodegen.build(with: codegenConfiguration)
    }
  }
```

### LINKED ISSUE #2302: [Swift Codegen] generates 'public' modifier is redundant for type alias declared in a public extension
## Bug report

There is a lot of `'public' modifier is redundant for type alias declared in a public extension` warning which makes it noisy. 

```swift
public extension CustomerGraphQL {
  public typealias ID = String // warning here

  public typealias SelectionSet = CustomerGraphQL_SelectionSet // warning here

  public typealias InlineFragment = CustomerGraphQL_InlineFragment // warning here

  public enum Schema: SchemaConfiguration { // warning here
    public static func objectType(forTypename __typename: String) -> Object.Type? {
      switch __typename {
      case "Query": return CustomerGraphQL.Query.self
      default: return nil
      }
    }
  }
}
```

## Versions

Please fill in the versions you're currently using: 

- `apollo-ios` SDK version: [1.0.0 Alpha 6](https://github.com/apollographql/apollo-ios/releases/tag/1.0.0-alpha.6)
- Xcode version: 13.4.1
- Swift version: 5.6.1
- Package manager: 5.6.1

## Steps to reproduce

Our generation command

```swift
  struct GenerateCode: ParsableCommand {
    static var configuration = CommandConfiguration(
      commandName: "generate",
      abstract: "Generates swift code from your schema + your operations based on information set up in the `GenerateCode` command.")

    func run() throws {
      /// The root of the target for which you want to generate code.
      let targetRootURL = SourceRootURL
        .apollo.childFolderURL(folderName: "customer-ios/graphql")

      /// The URL where the generated schema files will be written to.
      let schemaModuleURL = SourceRootURL
        .apollo.childFolderURL(folderName: "customer-ios/graphql")

      // Make sure the folders exists before trying to generate code.
      try FileManager.default.apollo.createDirectoryIfNeeded(atPath: targetRootURL.path)
      try FileManager.default.apollo.createDirectoryIfNeeded(atPath: schemaModuleURL.path)

      // Create the Codegen configuration object. For all configuration parameters see: https://www.apollographql.com/docs/ios/api/ApolloCodegenLib/structs/ApolloCodegenConfiguration/
      let codegenConfiguration = ApolloCodegenConfiguration(
        schemaName: "GraphQLApi", input: ApolloCodegenConfiguration.FileInput(schemaPath: SchemaOutputURL.path, searchPaths: ["\(targetRootURL.path)/**/*.graphql"]),
        output: ApolloCodegenConfiguration.FileOutput(
          schemaTypes: ApolloCodegenConfiguration.SchemaTypesFileOutput(
            path: schemaModuleURL.path,
            moduleType: .embeddedInTarget(name: "customer-ios"))
        )
      )

      // Actually attempt to generate code.
      try ApolloCodegen.build(with: codegenConfiguration)
    }
  }
```

### PR DESCRIPTION
**Pull request by calvincestari**
Fixes #2301 
Fixes #2302 

This PR updates the way schema module types are used in operation files when they are located with a `.relative` or `.absolute` placing them outside the schema module. Prior to this change the operation files would reference types that were inaccessible resulting in build errors.

### CODE REVIEW

File: Sources/AnimalKingdomAPI/AnimalKingdomAPI/Sources/Operations/AllAnimalsQuery.swift [hunk 1]
```diff
@@ -428,11 +428,11 @@ public class AllAnimalsQuery: GraphQLQuery {
         public static var __parentType: ParentType { .Object(AnimalKingdomAPI.Dog.self) }
         public static var selections: [Selection] { [
           .field("favoriteToy", String.self),
-          .field("birthdate", AnimalKingdomAPI.CustomDate?.self),
```
Comment (calvincestari) [inline Sources/AnimalKingdomAPI/AnimalKingdomAPI/Sources/Operations/AllAnimalsQuery.swift:431]: This namespace was removed because the configuration of the operation files in AnimalKingdom are `.inSchemaModule`.

File: Sources/ApolloCodegenLib/Templates/SelectionSetTemplate.swift [hunk 2]
```diff
@@ -5,12 +5,20 @@ struct SelectionSetTemplate {
 
   let schema: IR.Schema
   let isMutable: Bool
+  let config: ReferenceWrapped<ApolloCodegenConfiguration>
```
Comment (calvincestari) [inline Sources/ApolloCodegenLib/Templates/SelectionSetTemplate.swift:8]: I know we spoke about getting rid of `ReferenceWrapped`, and it is not used in some parts of this PR, but I think that should go into a separate PR and tackle it throughout the codegen codebase.

File: Sources/ApolloCodegenLib/Templates/TemplateRenderer.swift [hunk 3]
```diff
@@ -160,7 +162,7 @@ private struct ImportStatementTemplate {
     private static func shouldImportSchemaModule(
       _ config: ReferenceWrapped<ApolloCodegenConfiguration>
     ) -> Bool {
-      config.output.operations != .inSchemaModule && config.output.schemaTypes.isInModule
+      config.output.operations != .inSchemaModule
```
Comment (calvincestari) [inline Sources/ApolloCodegenLib/Templates/TemplateRenderer.swift:165]: Schema types always end up in some kind of module, whether it's one we create or on that we link to, but as soon as operation files are not part of that namespace the schema module must be imported.

File: Tests/ApolloCodegenInternalTestHelpers/MockApolloCodegenConfiguration.swift [hunk 4]
```diff
@@ -2,7 +2,7 @@
 
 extension ApolloCodegenConfiguration {
   public static func mock(
-    schemaName: String = "MockSchemaTypes",
+    schemaName: String = "TestSchema",
```
Comment (calvincestari) [inline Tests/ApolloCodegenInternalTestHelpers/MockApolloCodegenConfiguration.swift:5]: This change is because there are two places where the schema name is used; `IR.Schema.name` and `ApolloCodegenConfiguration.schemaName`. In production these can never differ because the IR schema name is initialized from the codegen config schema name. However in test mocks they can be initialized independently and we have been doing that which results in two different namespaces in expected test code. This 'standardizes' the default schema name across both mock objects.

I don't feel strongly about whether this needs to be 'fixed' but it might be worth looking into the places that don't have access to the config and use `IR.Schema.name`; can they be changed to use config instead. For now this is fine though.
