### PR TITLE
fix: Update graphql-js error handling

### LINKED ISSUE #3126: Update graphql-js error handling in Swift
By default graphql-js has a max error limit of 100, when this is surpassed it will return 101 errors with the last one being an "abort" error that you have exceeded the error limit. The Swift code is expecting all errors that return to have source location information and when the "abort" error comes through it causes a precondition failure and the user does not get the useful error logs they should.

To resolve this we need to update the error handling in Swift to properly handle this "abort" error to ensure the user is always receiving the proper error logs to aid in debugging errors.

### PR DESCRIPTION
**Pull request by BobaFetters**
-Updating the handling of graphql-js errors to check if source locations exist to determine how to process and display the error 
-This fixes the issue of reaching the max error limit of graphql-js

Closes #3126

### CODE REVIEW

File: Sources/ApolloCodegenLib/ApolloCodegen.swift [hunk 1]
```diff
@@ -305,8 +305,14 @@ public class ApolloCodegen {
     )
 
     guard graphqlErrors.isEmpty else {
-      let errorlines = graphqlErrors.flatMap({ $0.logLines })
-      CodegenLogger.log(String(describing: errorlines), logLevel: .error)
+      let errorlines = graphqlErrors.flatMap({
```
Comment (BobaFetters) [inline Sources/ApolloCodegenLib/ApolloCodegen.swift:308]: Thinking here is by making the `sourceLocations` optional and therefore the `logLines` optional, we can determine how to display a given error, so errors with `sourceLocations` get displayed as they always have, but errors without `sourceLocations` no longer cause a precondition failure and instead just have their `name` and `message` displayed to ensure the user always gets usable error information

Comment (AnthonyMDev) [reply Sources/ApolloCodegenLib/ApolloCodegen.swift:308]: This is an awesome solution!

File: Sources/ApolloCodegenLib/ApolloCodegen.swift [hunk 2]
```diff
@@ -305,8 +305,14 @@ public class ApolloCodegen {
...
+        if let logLines = $0.logLines {
+          return logLines
+        } else {
+          return ["[Error] \($0.name ?? "unknown"): \($0.message ?? "")"]
```
Comment (AnthonyMDev) [inline Sources/ApolloCodegenLib/ApolloCodegen.swift:312]: I believe the `[Error]` label is already prepended to the log by the `CodegenLogger`. So putting it here might make it display it twice in the actual log.

**Review by AnthonyMDev — APPROVED** [review]
Nice job! Just one thing to verify and this is good to go.

File: Sources/ApolloCodegenLib/ApolloCodegen.swift (hunk 2 above)
Comment (BobaFetters) [reply Sources/ApolloCodegenLib/ApolloCodegen.swift]: Good callout I'll remove that
