### PR TITLE
SelectionSet Codegen __typename fix - Closes #2955

### LINKED ISSUE #2955: Schemas with customized root operation type lead to execution errors due to incorrectly generated selection sets
### Summary

(Apologies for the terrible title. I'm struggling with the terminology and producing a concise title.)

Having custom root operation type names in the schema (see below) introduces a parsing error because the operation level selection set gets generated with a non-nil `__typename` field which won't actually exist in the operation's result JSON and leads to an execution error stating that a JSON value is missing for a key.

### Version

1.1.2

### Steps to reproduce the behavior

Here's an example schema I extracted from a test I wrote to confirm the issue:

```graphql
schema {
  query: RootQueryType
  mutation: RootMutationType
}

type RootQueryType {
  allAnimals: [Animal!]!
}

type RootMutationType {
  feedAnimal: Animal!
}

type Animal {
  fieldName: String!
}
```

Here's the document: 
```graphql
mutation FeedAnimal {
  feedAnimal {
    fieldName
  }
}
```

Here's the generated operation definition:

```swift
public struct Mutation: TestSchema.SelectionSet {
  public let __data: DataDict
  public init(_dataDict: DataDict) { __data = _dataDict }

  public static var __parentType: ApolloAPI.ParentType { TestSchema.Objects.RootMutationType }
  public static var __selections: [ApolloAPI.Selection] { [
    .field("__typename", String.self), // <== THIS SHOULDN'T BE HERE 
    .field("feedAnimal", FeedAnimal.self),
  ] }

  public var feedAnimal: FeedAnimal { __data["feedAnimal"] }

  /// FeedAnimal
  public struct FeedAnimal: TestSchema.SelectionSet {
    public let __data: DataDict
    public init(_dataDict: DataDict) { __data = _dataDict }

    public static var __parentType: ApolloAPI.ParentType { TestSchema.Objects.Animal }
    public static var __selections: [ApolloAPI.Selection] { [
      .field("__typename", String.self),
      .field("fieldName", String.self),
    ] }

    public var fieldName: String { __data["fieldName"] }
  }
}
```

Here's the an example of the underlying parsing error message from my actual app:
```
ApiError(
  errorDump: """
    ▿ ApolloCombine.GQLError.nonGQL
      ▿ nonGQL: Optional(Apollo.GraphQLExecutionError(path: __typename, underlying: ApolloAPI.JSONDecodingError.missingValue))
        ▿ some: Apollo.GraphQLExecutionError
          ▿ path: __typename
            ▿ head: Optional(Apollo.ResponsePath.(unknown context at $10116c1f4).Node)
              ▿ some: Apollo.ResponsePath.(unknown context at $10116c1f4).Node #0
                - previous: nil
                - key: "__typename"
                ▿ $__lazy_storage_$_joined: Optional("__typename")
                  - some: "__typename"
                - $__lazy_storage_$_components: nil
          - underlying: ApolloAPI.JSONDecodingError.missingValue
    
    """,
  file: "Networking/ApiClient.swift",
  line: 62,
  message: "The operation couldn’t be completed. (ApolloCombine.GQLError error 1.)"
)
```

The `SelectionSetTemplate` generates the `__typename` field based on the return value of:
```swift
private func shouldIncludeTypenameSelection(for scope: IR.ScopeDescriptor) -> Bool {
  return scope.scopePath.count == 1 && !scope.type.isRootFieldType
}
```

And here's how verifying a root field type is done in `GraphQLCompositeType`: 

```swift
public class GraphQLCompositeType: GraphQLNamedType {
  public override var debugDescription: String {
    "Type - \(name)"
  }

  var isRootFieldType: Bool {
    ["Query", "Mutation", "Subscription"].contains(name)
  }
}
```

Given the example schema above, an operation of type `RootMutationType` is not in the list `["Query", "Mutation", "Subscription"]`, which leads to the incorrectly generated `__typename` field in the operation's selection set. 

While I was trying to trace where the issue was stemming from, I cloned the repo and added a failing test case to `Tests/ApolloCodegenTests/CodeGeneration/Templates/SelectionSet/SelectionSetTemplateTests.swift`

```swift
func test__render_selections__givenCustomOperationRootSelectionSet_doesNotRenderTypenameSelection() throws {
  // given
  schemaSDL = """
  schema {
    query: RootQueryType
    mutation: RootMutationType
  }
  
  type RootQueryType {
    allAnimals: [Animal!]!
  }
  
  type RootMutationType {
    feedAnimal: Animal!
  }

  type Animal {
    fieldName: String!
  }
  """

  document = """
  mutation FeedAnimal {
    feedAnimal {
      fieldName
    }
  }
  """

  let expected = """
    public static var __selections: [ApolloAPI.Selection] { [
      .field("feedAnimal", FeedAnimal.self),
    ] }
  """

  // when
  try buildSubjectAndOperation(named: "FeedAnimal")
  let mutationRoot = try XCTUnwrap(
    operation[field: "mutation"] as? IR.EntityField
  )

  let actual = subject.render(field: mutationRoot)

  // then
  expect(actual).to(equalLineByLine(expected, atLine: 7, ignoringExtraLines: true))
}
```

### Logs

```shell
ApiError(
  errorDump: """
    ▿ ApolloCombine.GQLError.nonGQL
      ▿ nonGQL: Optional(Apollo.GraphQLExecutionError(path: __typename, underlying: ApolloAPI.JSONDecodingError.missingValue))
        ▿ some: Apollo.GraphQLExecutionError
          ▿ path: __typename
            ▿ head: Optional(Apollo.ResponsePath.(unknown context at $10116c1f4).Node)
              ▿ some: Apollo.ResponsePath.(unknown context at $10116c1f4).Node #0
                - previous: nil
                - key: "__typename"
                ▿ $__lazy_storage_$_joined: Optional("__typename")
                  - some: "__typename"
                - $__lazy_storage_$_components: nil
          - underlying: ApolloAPI.JSONDecodingError.missingValue
    
    """,
  file: "Networking/ApiClient.swift",
  line: 62,
  message: "The operation couldn’t be completed. (ApolloCombine.GQLError error 1.)"
)
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by BobaFetters**
-Adds data to CompilationResult from JS Frontend that includes the defined root types for query, mutation, and subscription -Uses the new root type data to set the `isRootFieldType` field on `GraphQLCompositeType` which is used when determining __typename selection generation for selection sets
-Added `isRootFieldType` calculation for `GraphQLCompositeType` on operations and fragments to the `init` of the `CompilationResult` object

### CODE REVIEW

File: Sources/ApolloCodegenLib/Frontend/CompilationResult.swift [hunk 1]
```diff
@@ -13,6 +15,31 @@ public class CompilationResult: JavaScriptObject {
 
   lazy var schemaDocumentation: String? = self["schemaDocumentation"]
   
+  required init(_ jsValue: JSValue, bridge: JavaScriptBridge) {
+    super.init(jsValue, bridge: bridge)
+    processRootTypes()
```
Comment (BobaFetters) [inline Sources/ApolloCodegenLib/Frontend/CompilationResult.swift:20]: Looking through the code, and where/how the `isRootFieldType` was originally used, without piping the new root type data through the pipeline, or updating the `GraphQLCompositeType` objects later in the pipeline, this seems like a good way to ensure all of the `GraphQLCompositeType` objects have their `isRootFieldType` updated before use.

File: Sources/ApolloCodegenLib/Frontend/auto_rollup.sh [hunk 2]
```diff
@@ -0,0 +1,7 @@
+#!/usr/bin/env bash
+
+SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
+output_file="$SCRIPT_DIR/ApolloCodegenFrontendBundle.swift"
+$( cd "$SCRIPT_DIR/Javascript" && rollup -c )
+minJS=$(cat "$SCRIPT_DIR/dist/ApolloCodegenFrontend.bundle.js")
+printf "%s%s%s" "let ApolloCodegenFrontendBundle: String = #\"" "$minJS" "\"#" > $output_file
```
Comment (AnthonyMDev) [inline Sources/ApolloCodegenLib/Frontend/auto_rollup.sh:7]: 😍

**Review by AnthonyMDev — APPROVED** [review]
This looks perfect! Thanks so much @BobaFetters!

**Comment by BobaFetters** [comment]
Switched back to draft to fix some tests

**Review by AnthonyMDev — APPROVED** [review]
👨‍🍳 🤌💋

File: .gitignore [hunk 3]
```diff
@@ -70,3 +70,6 @@ SwiftScripts/.build-**
 # Local generated packages we don't need in the main project
 Sources/AnimalKingdomAPI/Generated/Package.swift
 Sources/AnimalKingdomAPI/Generated/Package.resolved
+
+# Generated js files we don't need committed
+Sources/ApolloCodegenLib/Frontend/dist/
```
Comment (calvincestari) [inline .gitignore:75]: 👍🏻

File: Sources/ApolloCodegenLib/Frontend/JavaScript/src/compiler/index.ts [hunk 4]
```diff
@@ -71,6 +72,17 @@ export function compileToIR(
   const fragmentMap = new Map<String, ir.FragmentDefinition>();
   const referencedTypes = new Set<GraphQLNamedType>();
 
+  const queryType = schema.getQueryType() as GraphQLNamedType;
+  if (queryType === undefined) {
+    throw new GraphQLError("GraphQL Schema must contain a 'query' root type definition.", { });
```
Comment (calvincestari) [inline Sources/ApolloCodegenLib/Frontend/JavaScript/src/compiler/index.ts:77]: I don't think this we'd ever reach this stage. Since this is a spec violation it'll likely get caught by graphql-js validation before we start compiling the IR.

File: Sources/ApolloCodegenLib/Frontend/auto_rollup.sh (hunk 2 above)
Comment (calvincestari) [reply Sources/ApolloCodegenLib/Frontend/auto_rollup.sh:7]: Nicely done!

**Review by calvincestari — COMMENTED** [review]
Thanks for the awesome work @BobaFetters!
