### PR TITLE
fix: Test mock extension, fields and initializers should use module namespace

### LINKED ISSUE #2332: Test Mocks don't compile for `.embeddedInTarget` modules
Using a schema module type of `.embeddedInTarget` results in test mock objects not being generated with the correct namespace.

### PR DESCRIPTION
**Pull request by calvincestari**
Fixed #2332 

Test mock field types and convenience initializers were not being generated with the schema module namespace when required.

### CODE REVIEW

File: Sources/ApolloCodegenLib/Templates/RenderingHelpers/GraphQLType+Rendered.swift [hunk 1]
```diff
@@ -1,7 +1,10 @@
 extension GraphQLType {
 
   enum RenderContext {
+    /// Renders the type for use in an operation selection set.
     case selectionSetField(forceNonNull: Bool = false)
+    /// Renders the type for use in a test mock object.
+    case testMockField(forceNonNull: Bool = false)
```
Comment (AnthonyMDev) [inline Sources/ApolloCodegenLib/Templates/RenderingHelpers/GraphQLType+Rendered.swift:7]: Yay for `RenderContext`!

**Review by AnthonyMDev — APPROVED** [review]
Thanks so much for solving this! Tests look on point!
