### PR TITLE
Fix RootEntityType and FulfilledFragment name generation

### LINKED ISSUE #2962: Generated code is sometimes incomplete when using @include directive
### Summary

Codegen seems to omit some type when using @include directive on top level fragment.

### Version

1.1.2

### Steps to reproduce the behavior

Codegen seems to leave this line incomplete when using @include directive on top level fragment (in the definition of `IfFetchParticularEntity`):

`public typealias RootEntityType = `

```
query SomeQuery(
  $id: ID!
  $fetchParticularEntity: Boolean!
) {
  ...ParticularEntityFragment @include(if: $fetchParticularEntity)
  foo(id: $id) {
    ...SomeFragment
  }
}

```

Codegen doesn't crash or anything but the resulting code can't compile.

### Logs

_No response_

### Anything else?

I had no issue in version 1.0.7

### PR DESCRIPTION
**Pull request by AnthonyMDev**
Fully qualified names should be generated at all times for `FulfilledFragments` and `RootEntityType`. Due to the issue indicated in #2949 

Fully qualified names were not being calculated properly for fragments on the root of a query. Simplified the calculation of these by adding the fully qualified root type names to the root of the `FieldPathComponents`. This fixes #2962.

### CODE REVIEW

File: Sources/ApolloCodegenLib/IR/IR+OperationBuilder.swift [hunk 1]
```diff
@@ -12,7 +12,10 @@ extension IR {
 
     let rootEntity = Entity(
       rootTypePath: LinkedList(operationDefinition.rootType),
-      fieldPath: [.init(name: rootField.name, type: rootField.type)]
+      fieldPath: [.init(
+        name: "\(operationDefinition.generatedDefinitionName).Data",
```
Comment (AnthonyMDev) [inline Sources/ApolloCodegenLib/IR/IR+OperationBuilder.swift:16]: This is really hacky and a violation of separation of responsibilities. I'm working on a refactor that provides the information about the IR needed in order for the templates to format the name properly.

I'll be putting this PR back into draft.

File: Sources/ApolloCodegenLib/IR/IR.swift [hunk 2]
```diff
@@ -62,30 +62,87 @@ class IR {
   /// Multiple `SelectionSet`s may select fields on the same `Entity`. All `SelectionSet`s that will
   /// be selected on the same object share the same `Entity`.
   class Entity {
-    struct FieldPathComponent: Hashable {
-      let name: String
-      let type: GraphQLType
+
+    /// Represents the location within a GraphQL definition (operation or fragment) of an `Entity`.
+    struct Location: Hashable {
```
Comment (AnthonyMDev) [inline Sources/ApolloCodegenLib/IR/IR.swift:67]: In order to generate selection set names properly, an entity needs to be able to indicate where it is located in its definition. This includes needing to know _what_ definition (operation or fragment) it is defined in.

Previously, we were using a hacky solution of adding an initial `FieldPath` component that included the name of the fragment, or the operation type. This was being used to help properly generate the selection set names, but it was hacky for 2 reasons: 

1. It was making the "field path" not really accurate. Field path included a first component for the source definition that any code that was consuming the field path just needed to understand was there. Causing tight coupling of implementation code.
2. This partially put the responsibility of how we generate names in the templates into the IR. The IR should just represent the shape of the definitions, and the templates consume them to understand how to generate the correct code.

Representing the `Location` with a `SourceDefinition` and a `FieldPath` allows us to better represent the shape of the operations in the IR and allows the templates to do all the logic for formatting names of the Selection Sets.

File: Sources/ApolloCodegenLib/Frontend/CompilationResult.swift [hunk 3]
```diff
@@ -44,6 +44,10 @@ public class CompilationResult: JavaScriptObject {
       "\(name) on \(rootType.debugDescription)"
     }
 
+    public func hash(into hasher: inout Hasher) {
+      hasher.combine(name)
```
Comment (AnthonyMDev) [inline Sources/ApolloCodegenLib/Frontend/CompilationResult.swift:48]: There can never be 2 operations with the same name, as graphql-js would fail validation. So this is safe

File: Sources/ApolloCodegenLib/LinkedList.swift [hunk 4]
```diff
@@ -71,24 +75,25 @@ public struct LinkedList<T>: ExpressibleByArrayLiteral {
...
+  @_disfavoredOverload
   public init(_ headValue: T) {    
     self.init(head: HeadNode(value: headValue))
   }
 
-  public init(array: [T]) {
-    precondition(!array.isEmpty, "Cannot initialize LinkedList with an empty array. LinkedList must have at least one element.")
-    var segments = array
-    let headNode = HeadNode(value: segments.removeFirst())
+  public init<C: Collection<T>>(_ collection: C) {
```
Comment (AnthonyMDev) [inline Sources/ApolloCodegenLib/LinkedList.swift:83]: Made this function take in a generic collection instead of only an array. This allows us to pass in another linked list or an ordered set.

File: Sources/ApolloCodegenLib/Templates/SelectionSetTemplate.swift [hunk 5]
```diff
@@ -707,28 +706,116 @@ fileprivate extension IR.MergedSelections.MergedSource {
...
+    pluralizer: Pluralizer
+  ) -> String {
+    generatedSelectionSetName(
+      for: mergedSource.typeInfo,
+      format: format,
+      pluralizer: pluralizer
+    )
+  }
+
+  private static func generatedSelectionSetName(
```
Comment (AnthonyMDev) [inline Sources/ApolloCodegenLib/Templates/SelectionSetTemplate.swift:744]: This is the core of the changes in the template. The rest is mostly updating call sites to use these new functions.

This refactors the selection set name computation to account for the fact that the `fieldPath` no longer includes a component for the root definition.

File: Tests/ApolloCodegenTests/CodeGeneration/Templates/SelectionSet/SelectionSetTemplateTests.swift [hunk 6]
```diff
@@ -6037,6 +6037,153 @@ class SelectionSetTemplateTests: XCTestCase {
     expect(actual).to(equalLineByLine(expected, atLine: 1, ignoringExtraLines: true))
   }
 
+  func test__render_conditionalFragmentOnQueryRoot__rendersRootEntityType() throws {
```
Comment (AnthonyMDev) [inline Tests/ApolloCodegenTests/CodeGeneration/Templates/SelectionSet/SelectionSetTemplateTests.swift:6040]: These are the tests for the actual bug fix. The rest of the test changes are just refactoring for other minor API changes.

File: Sources/ApolloCodegenLib/IR/IR.swift (hunk 2 above)
Comment (BobaFetters) [reply Sources/ApolloCodegenLib/IR/IR.swift:67]: Like this change, especially helping separate responsibilities between the IR and Templates

**Review by BobaFetters — APPROVED** [review]
I think this looks good, nice work!

**Review by calvincestari — APPROVED** [review]
LGTM!
